### ISSUE TITLE
add support for building expansion modules not included by default

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/scripts#12]
src/svxlink/contrib/ are not being included in the builds

**Comment by abcrawford** [comment]
I will need a little more info on this. Is there a switch for the cmake command?

**Comment by abcrawford** [comment]
Also even when putting these in place it still may be a pain to enable the modules even as pure svxlink modules with out building a ORP folder for this. This is because there is a DB table for modules and module INI files that ORP uses to build configs. It will use these to build config files for each module as well as know what to include as enabled modules in the svxlink.conf file. The only way around this would be to do some hacking of the code and hard enable modules to prevent ORP from overwriting when other changes are made. 

The simplest thing to do would be to make basic companion ORP settings for the required modules, For those that don't need to have a settings page, the Parrot module would be the best to duplicate: /var/www/openrepeater/modules/Parrot then some basic entries may need to be made into the DB table. 

The module framework is only half developed at this point. But the ultimate goal is to allow uploading of modules as a zip file, then a class will unpack the zip file, validate the minimum requirements and put the ORP and SVXLink files into place. But that is in the future.

**Comment by Dloranger** [comment]
I sent the cmake mods via dm, i will dig them out again so we can do a diff
for a patch file on the 2 files.

My thought on the db would be to have a script check the folder for
existing config files and maybe just create an on/off list with no settings
(manual config file edits).  This would suffice until pages can be created
to interact with the settings.

**Comment by abcrawford** [comment]
For my own reference: https://github.com/sm0svx/svxlink/tree/master/src/svxlink/contrib
This has the cmake switches to include in the build when compiling.  See the readme...

**Comment by Dloranger** [comment]
No longer needed with the ability to upload modules targetted at ORP, script has method if someone wants to do it manually
