### ISSUE TITLE
Can not get to web page.

### ISSUE THREAD

**Issue by GabeHC** [OpenRepeater/scripts#74]
show up

This page isn’t working10.0.1.10 redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

RELOAD

**Comment by AD0ND** [comment]
I am having same issue. Did you ever find a resolution?

**Comment by AD0ND** [comment]
Still having the redirect issue with latest Chrome build.
Fresh compile of the script today, 6-20-23

**Comment by abcrawford** [comment]
Unfortunately this could be a generic error. I suspect it may have something to do with the some of the rewriting of the script (3.0.x-DEV branch)  and config updates for nginx. I haven't had any involvement in the script rewrite and haven't had a chance to debug myself. I suspect that you'd likely have better luck with the 2.2.x branch as that is better vetted...but that would install on top of Buster instead of Bullseye. The 3.0.x interface is quite there yet at the time of this post. At this time it's more for development then use. 2.1.3 and 2.2.x are usable installs.

**Comment by GabeHC** [comment]
Finally had it working. Did you make any changes. or I have done any different?
I am now have the new UI. Macros been add in, and some other customization options too.
I can setup RX audio device to WM8960, but not TX. there is no device show up for TX. how do I fix it?
 
![image](https://github.com/OpenRepeater/scripts/assets/5255323/b765020f-16f1-4cc0-8e45-b276fca8d1be)

**Comment by abcrawford** [comment]
@GabeHC Nothing has changed recently....you can verify by looking at the commit history for this branch. Keep in mind that the 3.0.x-DEV branch is not a stable release, it is a development branch and probably a better choice if you intend to help with development or like to experiment. the new UI is not fully built out yet. You should be able to still fall back to the old UI at this time. You can check linux directly from the command line to see if it is recognizing your output channel using an aplay -l command. If the OS cannot recognize it, then ORP will not pick it up either.

**Comment by Dloranger** [comment]
closing as a development issue, trying to use features before they have been developed/adapted to latest os/etc.
